msg=input('Digite algo: ')
print('O tipo primitivo desse valor é',type(msg))
print('Só tem espacos?',msg.isspace())
print('Ele é um numero?',msg.isnumeric())
print('E alfabetico?',msg.isalpha())
print('É alfanumerico?',msg.isalnum())
print('Está em maiuscula?',msg.isupper())
print('Está minusculas?',msg.islower())
print('Está capitalizada?',msg.istitle())
print('Todos os testes feitos, tchau!')